spring.application.name=demo-upi-backend

# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/demo_upi
spring.datasource.username=root
spring.datasource.password=${DB_PASS}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true