spring.application.name=demo-upi-backend

# Server
server.port=8080

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/demo_upi
spring.datasource.username=root
spring.datasource.password=7707

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OTP/ MAIL configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=badal4114@gmail.com
spring.mail.password=zpma zjmz ughd pssu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

